### ISSUE TITLE
Bishop doesn't move unless set again in the keys panel

### ISSUE THREAD

**Issue by Sentero-esp12** [artyompal/lichess_keyboard#1]
When I tried the extension, the bishop didn't move. But if I open the keys panel and click `space` while focusing on the Bishop field, it starts moving. It seems to do with capitalization of `Space`. Once I press `space` while in the bishop field, it saves non-capitalized

**Comment by artyompal** [comment]
Thanks again! Fixed in a823bfb

**Comment by Sentero-esp12** [comment]
Strange, this still seems to happen in the latest version. I guess it might not like `Shift`, `Spaces`, or there is a particular set of cookies that occurred in my case

**Comment by Sentero-esp12** [comment]
This still happens. `Space` doesn't move bishops unless I go to settings and set `Space` again. Try cleaning cookies with `document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });` and reloading the page. Does it reproduce?
