### ISSUE TITLE
King sometimes doesn't move

### ISSUE THREAD

**Issue by Sentero-esp12** [artyompal/lichess_keyboard#2]
Sometimes the king doesn't move while `Shift` is pressed. If I unpress and press Shift, it starts moving again.

**Comment by artyompal** [comment]
Sorry, I'm not able to reproduce this so far. Any tips? How often does it happen?

**Comment by Sentero-esp12** [comment]
Here's the recording. At 0:12 `Shift` is still pressed, but the king doesn't move. Then when I unpress and press `Shift`, it moves to `e2`. It happens almost every game against Stockfish. Also before pressing `Shift`, I think I had some pawn keys pressed, and while those keys were pressed, I pressed `Shift` 
https://user-images.githubusercontent.com/35060206/125055028-7e6e7980-e0af-11eb-9566-a93ae0a0ad1a.mp4

**Comment by artyompal** [comment]
Fixed by 5e493fb

**Comment by Sentero-esp12** [comment]
This still seems to happen with the latest version

**Comment by Sentero-esp12** [comment]
Still happens. Can be reproduced if `w` is pressed, then `Shift` is pressed without unpressing `w`. Pawns will move, but once you try to move the king (to a square to which no pawns can move) the king won't move. You have to unpress both keys and press `Shift` again for the king to move. If you only unpess and press `Shift`, while still holding `w` for pawn, the king will move only once and then it won't move anymore. Maybe this is by design, but this makes switching more difficult.
